spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./user
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
token-valid-time: 30 * 60 * 1000L
secret-key: hello-world-user-we-are-happy
